name: Auto arm
version: 0.3
author: firecopy
main: me.firecopy.autoarm.AutoArm
commands:
  autoarm:
    description: puts the strongest weapon and armor on the player.
    alias: [arm]
permissions:
  autoarm.arm:
    description: Gives the permission for auto arm.
    default: false